Fix URL encoding issue for filenames with special characters
rhnvrm/simples3 pull request #11
Opened 2021-02-02 06:55 UTC by jacksgt

Hey,

as discussed in #7 , I have ported over the path encoding function from minio-go.
Before that, I also added some tests to check the new & correct behavior.
I have run these tests against AWS S3 buckets (and they were successful), I still want to try it out with a Minio instance (but I didn't get around to it yet).

Feedback welcome. :-)

2021-02-02 08:38 UTC, rhnvrm requested changes
Hey, a few suggestions...

2021-02-02 08:38 UTC, rhnvrm commented on simples3.go
> +	path := bucket
Since this is an internal function, we can rename inside the function param itself to path.

2021-02-02 08:38 UTC, rhnvrm commented on simples3.go
> +// EncodePath encode the strings from UTF-8 byte representations to HTML hex escape sequences
/s/EncodePath/encodePath

2021-02-02 08:38 UTC, rhnvrm commented on simples3.go
> +		uri = s3.Endpoint + encodedPath
The TestCustomEndpoint unit test seems to be failing, could you please check it?

```
--- FAIL: TestCustomEndpoint (0.00s)
    simples3_test.go:340: S3.SetEndpoint() got = https://example.com
    simples3_test.go:346: S3.SetEndpoint() got = http://localhost:9000
    simples3_test.go:352: S3.SetEndpoint() got = https://example.com
```

2021-02-03 07:59 UTC, jacksgt commented
Hey, thank you for the review!
I hope I addresses all the issues. :-)

Still need to test with my Minio instance, though...

2021-02-03 11:46 UTC, rhnvrm commented
Hey

I just tested this with a local minio setup using their release binary and tests seem to pass. 

Documenting steps for future, I think we can use this for setting up automated testing. 

Had to create a testbucket from the UI (most likely this can be done using the cli). After that used the following env vars and ran `go test`.

```
AWS_S3_BUCKET=testbucket 
AWS_S3_ACCESS_KEY=minioadmin
AWS_S3_SECRET_KEY=minioadmin
AWS_S3_ENDPOINT=http://127.0.0.1:9000
```

2021-02-03 15:49 UTC, jacksgt commented
Adding integration tests in the CI with a local Minio server is a great idea! Let's tackle that in a separate PR.

I have squashed the commits, so from my side this is ready to be merged.

2021-02-03 15:56 UTC, rhnvrm approved these changes
LGTM :+1:

2021-02-03 15:57 UTC, merged

2021-02-03 15:58 UTC, jacksgt commented
Great, thanks for taking the time!